name: Build and Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2710
          - arch: aarch64_cortex-a72
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa72
          - arch: aarch64_generic
            sdk_url_path: http://downloads.openwrt.org/snapshots/targets/layerscape/armv8_64b
          - arch: arm_arm1176jzf-s_vfp
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2708
          - arch: arm_arm926ej-s
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/legacy
          - arch: arm_cortex-a15_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ipq806x/generic
          - arch: arm_cortex-a5-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/at91/sama5
          - arch: arm_cortex-a7_neon-vfpv4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm27xx/bcm2709
          - arch: arm_cortex-a8_vfpv3
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/sunxi/cortexa8
          - arch: arm_cortex-a9
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm53xx/generic
          - arch: arm_cortex-a9_neon
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/imx6/generic
          - arch: arm_cortex-a9_vfpv3-d16
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mvebu/cortexa9
          - arch: arm_fa526
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/gemini/generic
          - arch: arm_mpcore
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/oxnas/ox820
          - arch: arm_xscale
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/kirkwood/generic
          - arch: i386_pentium
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/legacy
          - arch: i386_pentium4
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/generic
          - arch: mips64_octeonplus
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/octeon/generic
          - arch: mipsel_24kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ramips/mt7620
          - arch: mipsel_24kc_24kf
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/pistachio/generic
          - arch: mipsel_74kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/mips74k
          - arch: mipsel_mips32
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm47xx/generic
          - arch: mips_24kc
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ath79/generic
          - arch: mips_mips32
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/bcm63xx/generic
          - arch: x86_64
            sdk_url_path: https://downloads.openwrt.org/snapshots/targets/x86/64
          # - arch: arc_arc700
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/arc770/generic
          # - arch: arc_archs
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/archs38/generic
          # - arch: armeb_xscale
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/ixp4xx/generic
          # - arch: powerpc_464fp
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/apm821xx/nand
          # - arch: powerpc_8540
          #   sdk_url_path: https://downloads.openwrt.org/snapshots/targets/mpc85xx/generic

    env:
      SDK_URL_PATH: ${{ matrix.sdk_url_path }}
      CACHE_DIR: ~/cache
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}:openwrt-passwall-build:${{ matrix.arch }}:release:cache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-passwall-build:${{ matrix.arch }}:cache:

      - name: Setup CCache
        uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ runner.os }}:openwrt-passwall-build:${{ matrix.arch }}:release:ccache:${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}:openwrt-passwall-build:${{ matrix.arch }}:ccache:

      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -yq gettext libncurses5-dev xsltproc

      - name: Prepare For Build
        run: |
          sdk_home="$(mktemp -d)"

          test -d ~/.ccache || mkdir -p ~/.ccache
          ln -sf ~/.ccache "$sdk_home/.ccache"

          echo "SDK_HOME=$sdk_home" >> $GITHUB_ENV
          echo "CONFIG_CCACHE=y" >> $GITHUB_ENV

      - name: Build package
        env:
          SIGN_PRIV_KEY: ${{ secrets.SIGN_PRIV_KEY }}
        run: ./compile.sh

      - name: Show CCache Status
        run: |
          eval "${{ env.SDK_HOME }}/staging_dir/host/bin/ccache -s"

      - name: Save Output Folder
        uses: actions/upload-artifact@v2
        with:
          name: openwrt-passwall-output-${{ matrix.arch }}
          path: dist
          retention-days: 7

      - name: Release and Upload Assets
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/**/*.ipk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch All Builds
        uses: actions/download-artifact@v2
        with:
          path: all-builds

      - name: Merge All Builds
        run: |
          mkdir dist
          for d in all-builds/*; do
            rsync -a $d/ dist
          done
          cp passwall.pub dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
