name: Build and Release

on:
  push:
    tags:
      - "test/**"

jobs:
  release:
    name: Build for ${{ matrix.arch }}-${{ matrix.sdk.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_cortex-a53
          - aarch64_cortex-a72
          - aarch64_generic
          - arc_archs
          - arm_arm1176jzf-s_vfp
          - arm_arm926ej-s
          - arm_cortex-a15_neon-vfpv4
          - arm_cortex-a5_vfpv4
          - arm_cortex-a7
          - arm_cortex-a7_neon-vfpv4
          - arm_cortex-a8_vfpv3
          - arm_cortex-a9
          - arm_cortex-a9_neon
          - arm_cortex-a9_vfpv3-d16
          - arm_fa526
          - arm_mpcore
          - arm_xscale
          - i386_pentium-mmx
          - i386_pentium4
          - mips64_octeonplus
          - mips_24kc
          - mips_4kec
          - mips_mips32
          - mipsel_24kc
          - mipsel_24kc_24kf
          - mipsel_74kc
          - mipsel_mips32
          - powerpc_464fp
          - powerpc_8540
          - x86_64
        sdk:
          - abi: snapshots/packages
            tag: snapshot
          - abi: releases/packages-21.02
            tag: openwrt-21.02
          - abi: releases/packages-22.03
            tag: openwrt-22.03
        include:
          - arch: arc_arc700
            sdk:
              abi: releases/packages-21.02
              tag: openwrt-21.02

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve Version
        id: ver
        run: |
          IFS=- read luci_ver pkgs_ver <<< $(cat upstream_version)
          echo "::set-output name=luci::$luci_ver"
          echo "::set-output name=pkgs::$pkgs_ver"

      - name: Build Package
        uses: MoetaYuko/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk.tag }}
          EXTRA_FEEDS: >-
            src-git|passwall_luci|https://github.com/xiaorouji/openwrt-passwall^${{ steps.ver.outputs.luci }}
            src-git|passwall_packages|https://github.com/xiaorouji/openwrt-passwall^${{ steps.ver.outputs.pkgs }}
          KEY_BUILD: ${{ secrets.SIGN_PRIV_KEY }}
          V: s

      - name: Tar Output Folder
        run: |
          DIST_DIR=$PWD/dist/${{ matrix.sdk.abi }}
          mkdir -p $DIST_DIR

          pushd bin/packages
          cp -r --parents */passwall* $DIST_DIR
          popd

          tar -cf dist.tar dist

      - name: Upload Output Folder
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-passwall-${{ matrix.arch }}-${{ matrix.sdk.tag }}
          path: dist.tar
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch All Builds
        uses: actions/download-artifact@v3
        with:
          path: all-builds

      - name: Merge All Builds
        run: |
          mkdir dist
          for d in all-builds/*; do
            tar -xf $d/dist.tar -C $d
            rsync -a $d/dist/ dist
          done
          cp passwall.pub dist

      - name: Deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.OSDN_DEPLOY_KEY }}
        with:
          src: 'dist/'
          dest: 'dianlujitao@storage.osdn.net:/storage/groups/o/op/openwrt-passwall-build/test/'
